application:
  bindAddress: :8452
  production: false
  debug: false
authentication:
  authority: https://algotiqa-server:8443/auth/realms/algotiqa
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
storage:
  folder: storage